from __future__ import annotations

from ..ta.constants import TRADING_DAYS_PER_YEAR

# Core numeric helpers
ZERO = 0.0
ONE = 1.0
EPSILON = 1e-12
VOL_ADJUST_EPSILON = 1e-9
BPS_DENOMINATOR = 10_000.0

# Trading/calendar conventions
START_DATE_SENTINEL = "1900-01-01"
DEFAULT_INITIAL_CASH = 100_000.0
ANNUAL_TRADING_DAYS = TRADING_DAYS_PER_YEAR

# Policy defaults
DEFAULT_REBALANCE_FREQ = "W-FRI"
DEFAULT_TARGET_VOL_RISK_ON = 0.22
DEFAULT_GROSS_CAP_RISK_ON = 1.0
DEFAULT_GROSS_CAP_RISK_OFF = 0.3
DEFAULT_MAX_WEIGHT = 0.45
DEFAULT_MIN_HOLD_DAYS = 10
DEFAULT_RISK_OFF_TARGET_VOL_MULTIPLIER = 0.5
DEFAULT_COVARIANCE_LOOKBACK = 252
DEFAULT_MIN_ADV_DOLLARS = 0.0
DEFAULT_MAX_TRADE_ADV_FRACTION = 0.10
DEFAULT_STOP_LOSS_PCT = 0.0
DEFAULT_TRAILING_STOP_PCT = 0.0
DEFAULT_COOLDOWN_DAYS = 0

# Regime model defaults
DEFAULT_REGIME_USE_BREADTH = True
DEFAULT_REGIME_BREADTH_MIN_FRAC = 0.5
DEFAULT_REGIME_MIN_CONFIRMATIONS = 3
DEFAULT_REGIME_REQUIRE_ANCHOR_TREND = True
DEFAULT_REGIME_DRAWDOWN_LOOKBACK = 252
DEFAULT_REGIME_DRAWDOWN_FLOOR = -0.20

# Default score weights
DEFAULT_WEIGHT_C_OVER_EMA200 = 0.35
DEFAULT_WEIGHT_EMA50_OVER_EMA200 = 0.25
DEFAULT_WEIGHT_MOM_252_21 = 0.25
DEFAULT_WEIGHT_VOL_ADJUSTED_MOMENTUM = 0.15
DEFAULT_WEIGHT_BREAKOUT55 = 0.10

# Default feature windows
MOM_LONG_WINDOW = 252
MOM_SHORT_WINDOW = 21
EMA_FAST_WINDOW = 50
EMA_SLOW_WINDOW = 200
VOL_WINDOW = 20
ATR_WINDOW = 14
BREAKOUT_WINDOW = 55
REGIME_SLOPE_DIFF = 10
REGIME_VOL_CEILING = 0.35

# Z-score/covariance defaults
ZSCORE_WINDOW = 252
ZSCORE_MIN_PERIODS = 60
SHRINKAGE_MIN_SAMPLES = 60
SHRINKAGE_LAMBDA = 0.15

# Slippage model defaults
SLIPPAGE_BASE_BPS = 5.0
SLIPPAGE_FALLBACK_BPS = 50.0
SLIPPAGE_IMPACT_COEFF = 40.0
SLIPPAGE_IMPACT_EXP = 0.5

# Regime labels
RISK_ON_FLAG = 1
RISK_OFF_FLAG = 0
RISK_ON_LABEL = "risk_on"
RISK_OFF_LABEL = "risk_off"

# Backtest event labels
EVENT_REBALANCE = "rebalance"
EVENT_RISK_EXIT = "risk_exit"
EVENT_REBALANCE_AND_RISK_EXIT = "rebalance+risk_exit"

# Backtest reason labels
REASON_STOP_LOSS = "stop_loss"
REASON_TRAILING_STOP = "trailing_stop"

# Recommendation labels/messages
ACTION_BUY = "BUY"
ACTION_SELL = "SELL"
ACTION_HOLD = "HOLD"
REASON_BELOW_EMA200 = "Below EMA200 filter"
REASON_SCORE_TEMPLATE = "Eligible with score {score:.3f}"
REASON_SCORE_UNAVAILABLE = "Eligible but score unavailable"
REASON_UNTRADABLE_PRICE = "Untradable price snapshot"
REASON_NO_ADV = "No liquidity data (ADV)"
REASON_ADV_BELOW_TEMPLATE = "ADV below minimum (${adv:,.0f} < ${min_adv:,.0f})"
REASON_LIQUIDITY_DISALLOWS = "Liquidity cap disallows trading"
REASON_LIQUIDITY_CAPPED_TEMPLATE = "Trade capped by liquidity ({fraction:.1%} ADV)"
